Fix issues when compiling with Clang
The one actual error is rather strange:

/vulkandriver/drivers/llpc/imported/llvm-dialects/include/llvm-dialects/Dialect/Dialect.h:215:13:
  error: reinterpret_cast from 'const void *' to 'void (*)(llvm_dialects::VisitorBuilder<llvm_dialects::VerifierState> &)'
         casts away qualifiers
            reinterpret_cast<const ExtensionT *>(m_extensions[i]));
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

One would think that `const ExtensionT *` with ExtensionT of function
type would have a const qualifier. Gcc seems to think so, but Clang
disagrees. Anyway, simply wrapping the function pointer in a struct
ought to be enough to make the problem go away.

Clang also warned about some missing virtual destructors. The warning in
Predicate was legitimate.